// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var code, file, func, lno, _i, _len, _ref, _results;
    _results = [];
    for (_i = 0, _len = _.length; _i < _len; _i++) {
      _ref = _[_i], file = _ref[0], lno = _ref[1], func = _ref[2], code = _ref[3];
      _results.push($('body').append($('<em>').text(file)).append($('<span>').text(': ')).append($('<mark>').text(lno)).append($('<span>').text('in')).append($('<strong>').text(func)).append($('<pre>').text(code)).append('<br>'));
    }
    return _results;
  });

}).call(this);
