// Generated by CoffeeScript 1.3.3
(function() {
  var _this = this;

  $(function() {
    var ws;
    _this.ajaws = true;
    $.ajax(location.href, {
      headers: {
        "W-Type": 'Get'
      }
    }).done(function(data) {
      _this.ajaws = false;
      document.open();
      document.write(data);
      return document.close();
    }).fail(function(data) {
      _this.ajaws = false;
      document.open();
      document.write(data.responseText);
      return document.close();
    });
    _this.ws = ws = new WebSocket("ws://localhost:" + _this.__ws_port);
    ws.onclose = function(m) {
      return console.log("close " + m);
    };
    ws.onmessage = function(m) {
      var cmd, data, pipe;
      pipe = m.data.indexOf('|');
      if (pipe > -1) {
        cmd = m.data.substr(0, pipe);
        data = m.data.substr(pipe + 1);
      } else {
        cmd = m.data;
      }
      switch (cmd) {
        case 'TRACE':
          _this.__w = JSON.parse(data);
          $('body').html('');
          return w_load();
        case 'PING':
          return ws.send('PONG');
        case 'JSON':
          _this._done(JSON.parse(data));
          return _this._done = null;
      }
    };
    ws.onerror = function(m) {
      return console.log("WebSocket error", m);
    };
    ws.onopen = function(m) {
      return console.log("WebSocket is open", m);
    };
    return _this.onbeforeunload = function() {
      try {
        ws.send('QUIT');
      } catch (e) {
        ({});
      }
      return void 0;
    };
  });

}).call(this);
